spring:
  application:
    name: guia-codechallenge

  datasource:
    url: jdbc:h2:mem:~/guia-codechallenge
    username: root
    password:

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

library:
  url: https://kotlinlang.org/docs/books.html